# stages:
#   - build_and_update_staging
#
# build_and_update_staging:
#   stage: build_and_update_staging
#   variables:
#     GIT_SUBMODULE_STRATEGY: normal
#   script:
#     - cp /home/gitlab-runner/.search-gfbio.env ./.env
#     - docker-compose -f staging.yml build --no-cache --force-rm
#     - docker-compose -f staging.yml down
#     - docker-compose -f staging.yml up -d
#   environment:
#     name: production
#     url: https://search.gfbio.dev/
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "main"'
#   tags:
#     - docker-lxc
#
# according to https://gitlab.gwdg.de/gfbio/cicd -------------------------------

before_script:
  - docker info

include:
  - project: gfbio/cicd
    file:
      - ".tag_release.yml"
stages:
  - tag_release

tag_release:
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - cp /home/gitlab-runner/.search-gfbio.env ./.env
    - docker-compose -f staging.yml build --no-cache --force-rm
    - docker-compose -f staging.yml down
    - docker-compose -f staging.yml up -d
  environment:
    name: production
    url: https://search.gfbio.org
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  tags:
    - docker-lxc
