include:
  - project: "gfbio/cicd"
    file:
      - ".create_merge_request_v3.yml"
      - ".tag_release.yml"
      - ".web_test_v3.yml"
      - ".hotfix_workflow.yml"
  - local: ".gitlab-ci/common/variables.yml"
  - local: ".gitlab-ci/common/tags.yml"

stages:
  - check_issue_type
  - create_merge_request
  - create_hotfix_merge_request
  - tag_release_check
  - tag_release
  - web_test_check
  - web_test_update
  - web_test_stop

create_merge_request:
  extends: .dev-denbi-tags
  variables:
    REVIEWERS: "2370 3999"

tag_release_check:
  extends: .dev-denbi-tags
  variables:
    MAIN_BRANCH_NAME: "production"

tag_release:
  script:
    - .gitlab-ci/scripts/tag_release.sh
  environment:
    name: production
    url: https://search.gfbio.org
  tags:
    - docker-lxc

web_test_update:
  variables:
    PROJECT_NAME: "search"
    COMPOSE_FILE: "web-test.yml"
  script:
    # - .gitlab-ci/scripts/web_test_update.sh
    - ISSUE_ID=$(awk -F- '{print $2}' <<< ${CI_COMMIT_REF_NAME})
    - TEST_NAME=$ISSUE_ID-$PROJECT_NAME
    - cp /home/gitlab-runner/.search-gfbio.node.env ./search/backend/.env
    - cp /home/gitlab-runner/.environment.prod.ts ./search/frontend/src/environments/environment.prod.ts
    - sed -i s/BRANCH/${TEST_NAME}/g $COMPOSE_FILE
    - docker-compose -f $COMPOSE_FILE build
    - docker stack rm $TEST_NAME || true
    - while [[ $(docker ps | grep $TEST_NAME | wc -l) > 0 ]]; do sleep 1; done
    - docker stack deploy -c $COMPOSE_FILE $TEST_NAME

web_test_stop:
  extends: .common-variables
