# stages:
#   - build_and_update_staging
#
# build_and_update_staging:
#   stage: build_and_update_staging
#   variables:
#     GIT_SUBMODULE_STRATEGY: normal
#   script:
#     - cp /home/gitlab-runner/.search-gfbio.env ./.env
#     - docker-compose -f staging.yml build --no-cache --force-rm
#     - docker-compose -f staging.yml down
#     - docker-compose -f staging.yml up -d
#   environment:
#     name: production
#     url: https://search.gfbio.dev/
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "main"'
#   tags:
#     - docker-lxc
#
# # according to https://gitlab.gwdg.de/gfbio/cicd -------------------------------

before_script:
  - docker info

include:
  - project: gfbio/cicd
    file:
      - ".create_merge_request.yml"
      - ".tag_release.yml"

stages:
  - create_merge_request
  - tag_release_check
  - tag_release

create_merge_request:
  tags:
    - dev-denbi

tag_release_check:
  variables:
    MAIN_BRANCH_NAME: "main"
  tags:
    - dev-denbi

tag_release:
  script:
    - cp /home/gitlab-runner/.search-gfbio.env ./.env
    - docker-compose -f staging.yml build --no-cache --force-rm
    - docker-compose -f staging.yml down
    - docker-compose -f staging.yml up -d
  environment:
    name: production
    url: https://search.gfbio.dev
  tags:
    - docker-lxc
