version: '3'
services:
  back:
    build: 
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: gfbio_search_back
    env_file:
      - ./.env
    networks:
      - internalProxy
    restart: always

  front:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
      args:
        SERVICE_HOST: 'https:\/\/search.gfbio.dev' # this str will be used in sed, so we need to escape /
    container_name: gfbio_search_front
    networks:
      - internalProxy
    restart: always

networks:
  internalProxy:
   external: true
