# comment
version: "3"
networks:
  internalProxy:
    external:
      name: internalProxy
services:
  back:
    hostname: gfbio_search_backend
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    image: gfbio_search_back
    env_file:
      - ./.env
    networks:
      - internalProxy
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.BRANCH-back.rule=Host(`BRANCH.test.gfbio.dev`) && PathPrefix(`/gfbio/`)"
      - "traefik.http.routers.BRANCH-back.entrypoints=web"
      - "traefik.http.services.BRANCH-back.loadbalancer.server.port=3000"
  front:
    depends_on:
      - back
    hostname: gfbio_search_frontend
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
      args:
        SERVICE_HOST: 'https:\/\/BRANCH.test.gfbio.dev' # this str will be used in sed, so we need to escape /
    image: gfbio_search_front
    env_file:
      - ./.env
    networks:
      - internalProxy
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.BRANCH-front.rule=Host(`BRANCH.test.gfbio.dev`)"
      - "traefik.http.routers.BRANCH-front.entrypoints=web"
      - "traefik.http.services.BRANCH-front.loadbalancer.server.port=80"
