version: "3"

networks:
  local:
  internalProxy:
    external:
      name: internalProxy

services:
  back:
    hostname: gfbio_search_backend
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    image: gfbio_search_back
    env_file:
      - ./.env
    networks:
      - local
    restart: always

  front:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
      args:
        SERVICE_HOST: 'https:\/\/BRANCH.test.gfbio.dev' # this str will be used in sed, so we need to escape /
    image: gfbio_search_front
    networks:
      - internalProxy
      - local
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.BRANCH-django.rule=Host(`BRANCH.test.gfbio.dev`)
      - traefik.http.routers.BRANCH-django.entrypoints=web
      - traefik.http.services.BRANCH-django.loadbalancer.server.port=80
