# Use an official Node runtime as a parent image
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json files and install dependencies
COPY ./search/angular/package*.json ./
RUN npm install

# Copy the Angular project files into the container
COPY ./search/angular/ .

# Expose the port the app runs on
EXPOSE 4200

# Define the command to run the app
CMD ["npm", "run", "start_dev"]
